wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.19.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1753886141
    t:
      1:
      - 1
      - 5
      - 53
      2:
      - 1
      - 5
      - 53
      3:
      - 1
      - 4
      - 19
      - 37
      - 42
      - 61
      4: 3.11.5
      5: 0.19.6
      13: linux-x86_64
epochs:
  desc: null
  value: 1000
