
#Model training
datafile_path: "./src/data/datasets/clean_peak_polarisation_intensity.npy"
num_epochs: 21000
name_model: "vq_peak_polarisation"

#Pretrained model
load_pretrained_model: null
load_epoch: null
load_shift: 0

#Data processing
batch_size: 2048
num_workers: 3
prefetch_factor: 16
pin_memory: True

#Optimizer
lr: 1e-3
weight_decay: 1e-4

#Scheduler
T_0: 100
T_mult: 1
eta_min: 1e-6
last_epoch: -1

# Quantile Transform model
qt_path: "./transforms/qt_peak_polarisation.pkl"

