#Model training
datafile_path: "./src/data/datasets/stokes_i.npy"
num_epochs: 3000
name_model: "vq_stokes_i"

#Data processing
batch_size: 512
num_workers: 5
prefetch_factor: 4
pin_memory: True

#Optimizer
lr: 1e-3
weight_decay: 1e-4

#Scheduler
T_0: 100
T_mult: 1
eta_min: 1e-6
last_epoch: -1

#wandb
wandb_id: null